// apps/web/src/components/SectionCard.tsx
import type { ReactNode } from 'react';

interface SectionCardProps {
  children: ReactNode;
  className?: string;
}

export function SectionCard({ children, className = '' }: SectionCardProps) {
  return (
    <div className={`bg-dark-card border border-dark-border rounded-xl p-6 ${className}`}>
      {children}
    </div>
  );
}

// packages/ui/src/lib/SectionCard.svelte
<script lang="ts">
import type { Snippet } from "svelte";

let {
	children,
	className = "",
}: {
	children: Snippet;
	className?: string;
} = $props();
</script>

<div class="bg-dark-card border border-dark-border rounded-xl shadow-sm shadow-black/20 p-6 lg:p-8 transition-shadow hover:shadow-md {className}">
  {@render children()}
</div>
