// apps/web/src/App.svelte
<script lang="ts">
import { relaySocket } from './lib/stores/relaySocket.svelte';
import type { ConnectionStatus, RelayInfo } from './utils/relay';
import { checkConnections, fetchNip11, normalizeUrl } from './utils/relay';
import './index.css';

// Components
import ConnectionPanel from './components/ConnectionPanel.svelte';
import ConnectionStatusPanel from './components/ConnectionStatusPanel.svelte';
import ErrorMessage from './components/ErrorMessage.svelte';
import EventFeed from './components/EventFeed.svelte';
import FilterBuilder from './components/FilterBuilder.svelte';
import LimitationsPanel from './components/LimitationsPanel.svelte';
import LoadingSpinner from './components/LoadingSpinner.svelte';
import NipBadgeGrid from './components/NipBadgeGrid.svelte';
import RelayProfile from './components/RelayProfile.svelte';
import EventVerifier from './components/verifier/EventVerifier.svelte';

type Tab = 'nip11' | 'stream' | 'verifier';

const POPULAR_RELAYS = [
  'relay.damus.io',
  'nos.lol',
  'relay.nostr.band',
  'relay.primal.net',
  'relay.nostr.info',
  'nostr.wine',
  'relay.snort.social',
];

// ─── State ───

let url = $state('');
let relayInfo = $state<RelayInfo | null>(null);
let connectionStatus = $state<ConnectionStatus | null>(null);
let loading = $state(false);
let error = $state<string | null>(null);
let activeTab = $state<Tab>('nip11');

const normalizedUrl = $derived(normalizeUrl(url));

// WebSocket store — reactive to URL changes via getter
const socket = relaySocket(() => normalizedUrl);

// ─── Derived State ───

const isNip11Tab = $derived(activeTab === 'nip11');
const isStreamTab = $derived(activeTab === 'stream');
const isVerifierTab = $derived(activeTab === 'verifier');
const hasRelay = $derived(normalizedUrl.length > 0);

// ─── Actions ───

async function handleFetch(targetUrl?: string) {
  const inputUrl = targetUrl || url;
  const normalized = normalizeUrl(inputUrl);
  if (!normalized) return;

  loading = true;
  error = null;
  relayInfo = null;
  connectionStatus = null;

  try {
    const [info, connStatus] = await Promise.all([
      fetchNip11(normalized),
      checkConnections(normalized),
    ]);
    relayInfo = info;
    connectionStatus = connStatus;
  } catch (e: unknown) {
    error = e instanceof Error ? e.message : 'Unknown error occurred';
    try {
      connectionStatus = await checkConnections(normalized);
    } catch {
      // Connection check also failed
    }
  } finally {
    loading = false;
  }
}

function handleSubmit(e: Event) {
  e.preventDefault();
  handleFetch();
}

function handleQuickPick(relay: string) {
  url = relay;
  handleFetch(relay);
}
</script>

<div class="min-h-screen bg-dark-bg">
  <!-- Header -->
  <header class="border-b border-dark-border bg-dark-card/50 backdrop-blur-sm sticky top-0 z-10">
    <div class="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center gap-3">
      <div
        class="w-9 h-9 rounded-lg bg-accent-dim border border-accent-border flex items-center justify-center"
      >
        <svg
          aria-hidden="true"
          class="w-5 h-5 text-accent"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      </div>
      <div>
        <h1 class="text-lg font-bold text-text-primary leading-tight">Relay Dog</h1>
        <p class="text-xs text-text-muted">Nostr relay inspector</p>
      </div>
      <span
        class="ml-auto text-[10px] font-mono px-2 py-1 rounded-full bg-dark-surface border border-dark-border text-text-muted"
      >
        Phase 3
      </span>
    </div>
  </header>

  <main class="max-w-3xl mx-auto px-4 sm:px-6 py-8">
    <!-- URL Input -->
    <form onsubmit={handleSubmit} class="mb-8 animate-fade-in">
      <div class="flex gap-2">
        <div class="relative flex-1">
          <div class="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted">
            <svg
              aria-hidden="true"
              class="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-width="2"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </div>
          <input
            type="text"
            bind:value={url}
            placeholder="wss://relay.damus.io"
            class="w-full pl-10 pr-4 py-3 rounded-xl bg-dark-card border border-dark-border text-text-primary placeholder:text-text-muted focus:outline-none focus:border-accent-border focus:ring-1 focus:ring-accent-border transition-all font-mono text-sm"
          />
        </div>
        <button
          type="submit"
          disabled={loading || !url.trim()}
          class="px-6 py-3 rounded-xl bg-accent text-white font-semibold text-sm hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed transition-all flex items-center gap-2"
        >
          {#if loading}
            <div
              class="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin"
            ></div>
            Inspecting
          {:else}
            <svg
              aria-hidden="true"
              class="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-width="2"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
            </svg>
            Inspect
          {/if}
        </button>
      </div>

      <!-- Quick pick relays -->
      <div class="mt-3 flex flex-wrap gap-1.5">
        <span class="text-xs text-text-muted mr-1 py-1">Try:</span>
        {#each POPULAR_RELAYS as relay (relay)}
          <button
            type="button"
            onclick={() => handleQuickPick(relay)}
            class="text-xs px-2.5 py-1 rounded-lg bg-dark-surface border border-dark-border text-text-muted hover:text-accent hover:border-accent-border transition-all"
          >
            {relay}
          </button>
        {/each}
      </div>
    </form>

    <!-- Tab Toggle -->
    <div class="flex gap-1 p-1 mb-6 rounded-xl bg-dark-surface border border-dark-border">
      <button
        type="button"
        onclick={() => (activeTab = 'nip11')}
        class="flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all {isNip11Tab
          ? 'bg-dark-card border border-dark-border text-text-primary'
          : 'text-text-muted hover:text-text-secondary'}"
      >
        NIP-11 Info
      </button>
      <button
        type="button"
        onclick={() => (activeTab = 'stream')}
        class="flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all {isStreamTab
          ? 'bg-dark-card border border-dark-border text-text-primary'
          : 'text-text-muted hover:text-text-secondary'}"
      >
        Live Stream
        {#if socket.events.length > 0}
          <span
            class="ml-2 text-[10px] font-mono px-1.5 py-0.5 rounded-full bg-accent-dim text-accent"
          >
            {socket.events.length.toLocaleString()}
          </span>
        {/if}
      </button>
      <button
        type="button"
        onclick={() => (activeTab = 'verifier')}
        class="flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all {isVerifierTab
          ? 'bg-dark-card border border-dark-border text-text-primary'
          : 'text-text-muted hover:text-text-secondary'}"
      >
        🔐 Event Verifier
      </button>
    </div>

    <!-- NIP-11 Tab -->
    {#if isNip11Tab}
      {#if loading}
        <LoadingSpinner />
      {/if}

      {#if !loading && error && !relayInfo}
        <ErrorMessage message={error} onRetry={() => handleFetch()} />
      {/if}

      {#if !loading && relayInfo}
        <div class="space-y-5">
          <RelayProfile info={relayInfo} />
          <NipBadgeGrid nips={relayInfo.supported_nips || []} />
          <LimitationsPanel limitation={relayInfo.limitation} />
          <ConnectionStatusPanel status={connectionStatus} />

          <!-- Raw JSON toggle -->
          <details class="group">
            <summary
              class="cursor-pointer text-sm text-text-muted hover:text-text-secondary transition-colors flex items-center gap-2 py-2"
            >
              <svg
                aria-hidden="true"
                class="w-4 h-4 transition-transform group-open:rotate-90"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
              </svg>
              Raw NIP-11 JSON
            </summary>
            <pre
              class="mt-2 p-4 rounded-xl bg-dark-surface border border-dark-border text-xs text-text-secondary overflow-x-auto font-mono leading-relaxed">{JSON.stringify(
                relayInfo,
                null,
                2,
              )}</pre>
          </details>

          <!-- Error details if connection had issues -->
          {#if !loading && error && relayInfo}
            <div
              class="px-4 py-3 rounded-xl bg-warning-dim border border-warning/20 text-sm text-warning"
            >
              ⚠ {error}
            </div>
          {/if}
        </div>
      {/if}

      {#if !loading && !error && !relayInfo}
        <div class="flex flex-col items-center justify-center py-20 text-center animate-fade-in">
          <div
            class="w-20 h-20 rounded-2xl bg-dark-card border border-dark-border flex items-center justify-center mb-6"
          >
            <svg
              aria-hidden="true"
              class="w-10 h-10 text-text-muted"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-width="1"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
              <circle cx="12" cy="12" r="10" />
            </svg>
          </div>
          <h2 class="text-xl font-semibold text-text-primary mb-2">
            Inspect a Nostr Relay
          </h2>
          <p class="text-text-muted text-sm max-w-sm mb-6">
            Enter a relay URL above to fetch its NIP-11 info document, check connection status, and
            explore supported features.
          </p>
          <div class="flex flex-wrap justify-center gap-2 text-xs text-text-muted">
            <span class="px-3 py-1.5 rounded-lg bg-dark-card border border-dark-border">
              NIP-11 Info
            </span>
            <span class="px-3 py-1.5 rounded-lg bg-dark-card border border-dark-border">
              Connection Checks
            </span>
            <span class="px-3 py-1.5 rounded-lg bg-dark-card border border-dark-border">
              NIP Badge Grid
            </span>
          </div>
        </div>
      {/if}
    {/if}

    <!-- Live Stream Tab -->
    {#if isStreamTab}
      <div class="space-y-5 animate-fade-in">
        <ConnectionPanel
          relayUrl={normalizedUrl}
          status={socket.status}
          eventCount={socket.events.length}
          eose={socket.eose}
          error={socket.error}
          notices={socket.notices}
          onConnect={socket.connect}
          onDisconnect={socket.disconnect}
        />
        <FilterBuilder connected={socket.status === 'connected'} onSend={socket.send} />
        <EventFeed events={socket.events} />
      </div>
    {/if}

    <!-- Event Verifier Tab -->
    {#if isVerifierTab}
      <EventVerifier />
    {/if}
  </main>

  <!-- Footer -->
  <footer class="border-t border-dark-border mt-auto">
    <div
      class="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between text-xs text-text-muted"
    >
      <span>Relay Dog · Nostr Relay Inspector</span>
      <span class="font-mono">v0.1.0</span>
    </div>
  </footer>
</div>

// apps/web/src/App.tsx
import { useCallback, useState } from 'react';
import {
  ConnectionStatusPanel,
  ErrorMessage,
  LimitationsPanel,
  LoadingSpinner,
  NipBadgeGrid,
  RelayProfile,
} from './components';
import { ConnectionPanel } from './components/ConnectionPanel';
import { EventFeed } from './components/EventFeed';
import { FilterBuilder } from './components/FilterBuilder';
import { useRelaySocket } from './hooks/useRelaySocket';
import type { ConnectionStatus, RelayInfo } from './utils/relay';
import { checkConnections, fetchNip11, normalizeUrl } from './utils/relay';
import './index.css';

type Tab = 'nip11' | 'stream';

const POPULAR_RELAYS = [
  'relay.damus.io',
  'nos.lol',
  'relay.nostr.band',
  'relay.primal.net',
  'relay.nostr.info',
  'nostr.wine',
  'relay.snort.social',
];

function App() {
  const [url, setUrl] = useState('');
  const [relayInfo, setRelayInfo] = useState<RelayInfo | null>(null);
  const [connectionStatus, setConnectionStatus] = useState<ConnectionStatus | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<Tab>('nip11');

  const normalizedUrl = normalizeUrl(url);

  const {
    status,
    events,
    send,
    connect,
    disconnect,
    eose,
    notices,
    error: wsError,
  } = useRelaySocket(normalizedUrl);

  const handleFetch = useCallback(
    async (targetUrl?: string) => {
      const inputUrl = targetUrl || url;
      const normalized = normalizeUrl(inputUrl);
      if (!normalized) return;

      setLoading(true);
      setError(null);
      setRelayInfo(null);
      setConnectionStatus(null);

      try {
        const [info, connStatus] = await Promise.all([
          fetchNip11(normalized),
          checkConnections(normalized),
        ]);
        setRelayInfo(info);
        setConnectionStatus(connStatus);
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : 'Unknown error occurred');
        try {
          const connStatus = await checkConnections(normalized);
          setConnectionStatus(connStatus);
        } catch {
          // Connection check also failed
        }
      } finally {
        setLoading(false);
      }
    },
    [url],
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    handleFetch();
  };

  const isNip11Tab = activeTab === 'nip11';
  const isStreamTab = activeTab === 'stream';
  const hasRelay = normalizedUrl.length > 0;

  return (
    <div className="min-h-screen bg-dark-bg">
      {/* Header */}
      <header className="border-b border-dark-border bg-dark-card/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-accent-dim border border-accent-border flex items-center justify-center">
            <svg
              aria-hidden="true"
              className="w-5 h-5 text-accent"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <div>
            <h1 className="text-lg font-bold text-text-primary leading-tight">Relay Dog</h1>
            <p className="text-xs text-text-muted">Nostr relay inspector</p>
          </div>
          <span className="ml-auto text-[10px] font-mono px-2 py-1 rounded-full bg-dark-surface border border-dark-border text-text-muted">
            Phase 2
          </span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8">
        {/* URL Input */}
        <form onSubmit={handleSubmit} className="mb-8 animate-fade-in">
          <div className="flex gap-2">
            <div className="relative flex-1">
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted">
                <svg
                  aria-hidden="true"
                  className="w-4 h-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                  />
                </svg>
              </div>
              <input
                type="text"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="wss://relay.damus.io"
                className="w-full pl-10 pr-4 py-3 rounded-xl bg-dark-card border border-dark-border text-text-primary placeholder:text-text-muted focus:outline-none focus:border-accent-border focus:ring-1 focus:ring-accent-border transition-all font-mono text-sm"
              />
            </div>
            <button
              type="submit"
              disabled={loading || !url.trim()}
              className="px-6 py-3 rounded-xl bg-accent text-white font-semibold text-sm hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed transition-all flex items-center gap-2"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin" />
                  Inspecting
                </>
              ) : (
                <>
                  <svg
                    aria-hidden="true"
                    className="w-4 h-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M13 10V3L4 14h7v7l9-11h-7z"
                    />
                  </svg>
                  Inspect
                </>
              )}
            </button>
          </div>

          {/* Quick pick relays */}
          <div className="mt-3 flex flex-wrap gap-1.5">
            <span className="text-xs text-text-muted mr-1 py-1">Try:</span>
            {POPULAR_RELAYS.map((r) => (
              <button
                key={r}
                type="button"
                onClick={() => {
                  setUrl(r);
                  handleFetch(r);
                }}
                className="text-xs px-2.5 py-1 rounded-lg bg-dark-surface border border-dark-border text-text-muted hover:text-accent hover:border-accent-border transition-all"
              >
                {r}
              </button>
            ))}
          </div>
        </form>

        {/* Tab Toggle */}
        {hasRelay && (
          <div className="flex gap-1 p-1 mb-6 rounded-xl bg-dark-surface border border-dark-border">
            <button
              type="button"
              onClick={() => setActiveTab('nip11')}
              className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all ${
                isNip11Tab
                  ? 'bg-dark-card border border-dark-border text-text-primary'
                  : 'text-text-muted hover:text-text-secondary'
              }`}
            >
              NIP-11 Info
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('stream')}
              className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all ${
                isStreamTab
                  ? 'bg-dark-card border border-dark-border text-text-primary'
                  : 'text-text-muted hover:text-text-secondary'
              }`}
            >
              Live Stream
              {events.length > 0 && (
                <span className="ml-2 text-[10px] font-mono px-1.5 py-0.5 rounded-full bg-accent-dim text-accent">
                  {events.length.toLocaleString()}
                </span>
              )}
            </button>
          </div>
        )}

        {/* NIP-11 Tab */}
        {isNip11Tab && (
          <>
            {loading && <LoadingSpinner />}

            {!loading && error && !relayInfo && (
              <ErrorMessage message={error} onRetry={() => handleFetch()} />
            )}

            {!loading && relayInfo && (
              <div className="space-y-5">
                <RelayProfile info={relayInfo} />
                <NipBadgeGrid nips={relayInfo.supported_nips || []} />
                <LimitationsPanel limitation={relayInfo.limitation} />
                <ConnectionStatusPanel status={connectionStatus} />

                {/* Raw JSON toggle */}
                <details className="group">
                  <summary className="cursor-pointer text-sm text-text-muted hover:text-text-secondary transition-colors flex items-center gap-2 py-2">
                    <svg
                      aria-hidden="true"
                      className="w-4 h-4 transition-transform group-open:rotate-90"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                    </svg>
                    Raw NIP-11 JSON
                  </summary>
                  <pre className="mt-2 p-4 rounded-xl bg-dark-surface border border-dark-border text-xs text-text-secondary overflow-x-auto font-mono leading-relaxed">
                    {JSON.stringify(relayInfo, null, 2)}
                  </pre>
                </details>

                {/* Error details if connection had issues */}
                {!loading && error && relayInfo && (
                  <div className="px-4 py-3 rounded-xl bg-warning-dim border border-warning/20 text-sm text-warning">
                    ⚠ {error}
                  </div>
                )}
              </div>
            )}

            {!loading && !error && !relayInfo && (
              <div className="flex flex-col items-center justify-center py-20 text-center animate-fade-in">
                <div className="w-20 h-20 rounded-2xl bg-dark-card border border-dark-border flex items-center justify-center mb-6">
                  <svg
                    aria-hidden="true"
                    className="w-10 h-10 text-text-muted"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={1}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M13 10V3L4 14h7v7l9-11h-7z"
                    />
                    <circle cx="12" cy="12" r="10" />
                  </svg>
                </div>
                <h2 className="text-xl font-semibold text-text-primary mb-2">
                  Inspect a Nostr Relay
                </h2>
                <p className="text-text-muted text-sm max-w-sm mb-6">
                  Enter a relay URL above to fetch its NIP-11 info document, check connection
                  status, and explore supported features.
                </p>
                <div className="flex flex-wrap justify-center gap-2 text-xs text-text-muted">
                  <span className="px-3 py-1.5 rounded-lg bg-dark-card border border-dark-border">
                    NIP-11 Info
                  </span>
                  <span className="px-3 py-1.5 rounded-lg bg-dark-card border border-dark-border">
                    Connection Checks
                  </span>
                  <span className="px-3 py-1.5 rounded-lg bg-dark-card border border-dark-border">
                    NIP Badge Grid
                  </span>
                </div>
              </div>
            )}
          </>
        )}

        {/* Live Stream Tab */}
        {isStreamTab && (
          <div className="space-y-5 animate-fade-in">
            <ConnectionPanel
              relayUrl={normalizedUrl}
              status={status}
              eventCount={events.length}
              eose={eose}
              error={wsError}
              notices={notices}
              onConnect={connect}
              onDisconnect={disconnect}
            />
            <FilterBuilder connected={status === 'connected'} onSend={send} />
            <EventFeed events={events} />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-dark-border mt-auto">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between text-xs text-text-muted">
          <span>Relay Dog · Nostr Relay Inspector</span>
          <span className="font-mono">v0.1.0</span>
        </div>
      </footer>
    </div>
  );
}

export default App;
