// apps/web/src/components/LoadingSpinner.svelte
<script lang="ts">
// Pure presentational component — no props needed
</script>

<div class="flex items-center justify-center py-16">
  <div class="relative">
    <div class="w-12 h-12 rounded-full border-2 border-dark-border"></div>
    <div
      class="absolute inset-0 w-12 h-12 rounded-full border-2 border-transparent border-t-accent animate-spin"
    ></div>
  </div>
</div>

// apps/web/src/components/LoadingSpinner.tsx
export function LoadingSpinner() {
  return (
    <div className="flex items-center justify-center py-16">
      <div className="relative">
        <div className="w-12 h-12 rounded-full border-2 border-dark-border" />
        <div className="absolute inset-0 w-12 h-12 rounded-full border-2 border-transparent border-t-accent animate-spin" />
      </div>
    </div>
  );
}
