// apps/web/src/components/shared/SectionCard.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import * as Card from "$lib/components/ui/card";

let {
	children,
	className = "",
}: {
	children?: Snippet;
	className?: string;
} = $props();
</script>

<Card.Root class="rounded-xl border-dark-border bg-dark-card shadow-sm shadow-black/20 transition-shadow hover:shadow-md {className}">
  <Card.Content class="p-6 lg:p-8">
    {@render children?.()}
  </Card.Content>
</Card.Root>

// apps/web/src/components/SectionCard.tsx
import type { ReactNode } from 'react';

interface SectionCardProps {
  children: ReactNode;
  className?: string;
}

export function SectionCard({ children, className = '' }: SectionCardProps) {
  return (
    <div className={`bg-dark-card border border-dark-border rounded-xl p-6 ${className}`}>
      {children}
    </div>
  );
}
