// packages/ui/src/lib/StatusDot.svelte
<script lang="ts">
type CheckStatus = "success" | "error" | "checking" | "pending";

let { status }: { status: CheckStatus } = $props();

const COLORS: Record<CheckStatus, string> = {
	success: "bg-success",
	error: "bg-error",
	checking: "bg-warning",
	pending: "bg-text-muted",
};
</script>

<span
  aria-hidden="true"
  class="inline-block w-2.5 h-2.5 rounded-full {COLORS[status] || COLORS.pending} {status === 'checking' ? 'animate-pulse-dot' : ''}"
></span>

// apps/web/src/components/StatusDot.tsx
import type { CheckStatus } from '../utils/relay';

const COLORS: Record<CheckStatus, string> = {
  success: 'bg-success',
  error: 'bg-error',
  checking: 'bg-warning',
  pending: 'bg-text-muted',
};

export function StatusDot({ status }: { status: CheckStatus }) {
  return (
    <span
      aria-hidden="true"
      className={`inline-block w-2.5 h-2.5 rounded-full ${COLORS[status] || COLORS.pending} ${
        status === 'checking' ? 'animate-pulse-dot' : ''
      }`}
    />
  );
}
