// apps/web/src/components/StatusDot.tsx
import type { CheckStatus } from '../utils/relay';

const COLORS: Record<CheckStatus, string> = {
  success: 'bg-success',
  error: 'bg-error',
  checking: 'bg-warning',
  pending: 'bg-text-muted',
};

export function StatusDot({ status }: { status: CheckStatus }) {
  return (
    <span
      aria-hidden="true"
      className={`inline-block w-2.5 h-2.5 rounded-full ${COLORS[status] || COLORS.pending} ${
        status === 'checking' ? 'animate-pulse-dot' : ''
      }`}
    />
  );
}

// apps/web/src/lib/components/ui/status-dot/status-dot.svelte
<script lang="ts">
type CheckStatus = 'success' | 'error' | 'checking' | 'pending';

let { status, class: className }: { status: CheckStatus; class?: string } = $props();

const COLORS: Record<CheckStatus, string> = {
  success: 'bg-success',
  error: 'bg-error',
  checking: 'bg-warning',
  pending: 'bg-text-muted',
};
</script>

<span
  data-slot="status-dot"
  aria-hidden="true"
  class="inline-block h-2.5 w-2.5 rounded-full {COLORS[status]} {status === 'checking' ? 'animate-pulse-dot' : ''} {className ?? ''}"
></span>
